### ISSUE TITLE
请问项目还在维护吗

### ISSUE THREAD

**Issue by forfuns** [logbird/360yunpan#5]
你好，360云盘准备关闭了，现在想导出里面的资料，恰好手上有树莓派还有服务器，想用一个程序跑一晚将数据导出到本地，而不是PC用360客户端进行导出，请问项目还继续维护，能实现吗，谢谢！

**Comment by CBDlkl** [comment]
我也是，请问项目还在维护吗？我准备导出文件到服务器上。

**Comment by logbird** [comment]
近期我找时间在看一下吧。。


发自网易邮箱大师
在2016年11月10日 12:29，愤怒的TryCatch 写道:

我也是，请问项目还在维护吗？我准备导出文件到服务器上。

**Comment by logbird** [comment]
可以试试 是否Ok。
